### ISSUE TITLE
No matches found for -

### ISSUE THREAD

**Issue by MikuMikuMe** [lavalink-devs/Lavalink#717]
## Description
Can't find match for the song

## Version info
**Client used:** https://github.com/SudhanPlayz/Discord-MusicBot

Output of `java -version`:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
```

```
2022-08-22 14:54:16.839 ERROR 264186 --- [XNIO-1 I/O-1] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:590) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1063) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:978) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:234) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:223) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:228) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:387) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:107) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:494) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2022-08-22 14:54:16.840 ERROR 264186 --- [XNIO-1 I/O-1] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:590) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1063) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:978) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:234) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:223) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:228) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:387) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:107) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:494) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2022-08-22 14:54:16.840 ERROR 264186 --- [XNIO-1 I/O-1] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:590) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1063) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:978) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:234) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:223) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:228) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:387) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:107) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:494) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
```

Used both 3.5-rc3 and rc4

**Comment by aikaterna** [comment]
Can you provide a whole log? The part you posted is not really relevant to song searching.

**Comment by MikuMikuMe** [comment]
[spring.log](https://github.com/freyacodes/Lavalink/files/9394867/spring.log)


> Can you provide a whole log? The part you posted is not really relevant to song searching.

Please take a look, thank you.

**Comment by devoxin** [comment]
You're on a very outdated build (with Lavaplayer 1.3.96-original). Please try updating first to see if this solves your issue. If your issue persists, please upload the logs from the updated build.

**Comment by MikuMikuMe** [comment]
> You're on a very outdated build (with Lavaplayer 1.3.96-original). Please try updating first to see if this solves your issue. If your issue persists, please upload the logs from the updated build.

But the bot was running fine 12h ago with the same configuration.

**Comment by devoxin** [comment]
Either way, we can't be certain that your issue isn't caused by outdated dependencies or missing fixes. I would hazard a guess your build is actually `3.4` which is approaching a year old. It is advised that you update to rule out an outdated build being the issue. This is generally best practice when reporting issues.

**Comment by MikuMikuMe** [comment]
> Either way, we can't be certain that your issue isn't caused by outdated dependencies or missing fixes. I would hazard a guess your build is actually `3.4` which is approaching a year old. It is advised that you update to rule out an outdated build being the issue. This is generally best practice when reporting issues.

I have deployed [v3.5-rc4](https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc4) and same thing happened. I tried many public lavalink servers and also get the same result. Another public server hoster have confirm he is getting the same error.

**Comment by topi314** [comment]
Can you post your full logs again?

**Comment by MikuMikuMe** [comment]
> Can you post your full logs again?

I deleted the whole lavalink folder and installed [v3.5-rc4](https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc4), no logs so far. Sorry, I only have the log file with 3.4, which I posted before.

**Comment by topi314** [comment]
You can also just look at your console

**Comment by MikuMikuMe** [comment]
> You can also just look at your console

Thats all I have. I think it might be youtube's problem.
```
2022-08-22 19:16:29.403  INFO 15851 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 16.0.1 on lava.islantay.tk with PID 15851 (/root/lavalink/Lavalink.jar started by root in /root/lavalink)
2022-08-22 19:16:29.412  INFO 15851 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 19:16:31.306  INFO 15851 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.704 seconds (JVM running for 3.459)
2022-08-22 19:16:31.311  INFO 15851 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2022-08-22 19:16:31.407  INFO 15851 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

	Version:        3.5-rc4
	Build time:     18.08.2022 16:03:31 UTC
	Branch          HEAD
	Commit:         b69f613
	Commit time:    18.08.2022 15:52:23 UTC
	JVM:            16.0.1
	Lavaplayer      1.3.98.4-original

2022-08-22 19:16:31.423  INFO 15851 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 19:16:32.563  WARN 15851 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-22 19:16:32.604  INFO 15851 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-22 19:16:32.606  INFO 15851 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1172 ms
2022-08-22 19:16:32.721  WARN 15851 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-22 19:16:33.097  INFO 15851 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-22 19:16:33.295  INFO 15851 --- [           main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
2022-08-22 19:16:33.295  INFO 15851 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-22 19:16:33.298  INFO 15851 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-22 19:16:33.306  INFO 15851 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-22 19:16:33.757  INFO 15851 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2022-08-22 19:16:33.777  INFO 15851 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2022-08-22 19:16:33.787  INFO 15851 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2022-08-22 19:16:33.916  INFO 15851 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2022-08-22 19:16:33.970  INFO 15851 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8880 (http)
2022-08-22 19:16:33.985  INFO 15851 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.668 seconds (JVM running for 6.137)
2022-08-22 19:16:33.987  INFO 15851 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2022-08-22 19:16:34.189  INFO 15851 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-22 19:16:34.191  INFO 15851 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-22 19:16:34.195  INFO 15851 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2022-08-22 19:16:34.236  INFO 15851 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58204
2022-08-22 19:16:34.339  INFO 15851 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from WaveLink
2022-08-22 19:16:34.379  INFO 15851 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "216ea91636bf9f36", "timeout": 60}
2022-08-22 19:16:34.385  INFO 15851 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58206
2022-08-22 19:16:34.400  INFO 15851 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:16:34.447  INFO 15851 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58208
2022-08-22 19:16:34.459  INFO 15851 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58210
2022-08-22 19:16:34.461  INFO 15851 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:16:34.464  INFO 15851 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:16:34.476  INFO 15851 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58212
2022-08-22 19:16:34.491  INFO 15851 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:17:07.487 ERROR 15851 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:60992
2022-08-22 19:17:07.724  INFO 15851 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:60994
2022-08-22 19:17:07.727  INFO 15851 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from Wavelink
2022-08-22 19:18:13.118  INFO 15851 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:55914
2022-08-22 19:18:13.121  INFO 15851 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:18:19.047  INFO 15851 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"553794295526588434","volume":100}
2022-08-22 19:18:19.085  INFO 15851 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:never gonna give you up"
2022-08-22 19:18:19.096  INFO 15851 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found
2022-08-22 19:18:19.377  INFO 15851 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"4f51ceca3a5a0e307d935fdf17d20969","op":"voiceUpdate","guildId":"553794295526588434","event":{"token":"3c72c06fbcb71dac","guild_id":"553794295526588434","endpoint":"us-west6586.discord.media:443"}}
```

**Comment by topi314** [comment]
That's exactly what I wanted
Do you perhaps by any chance have yt or yt search disabled?

**Comment by MikuMikuMe** [comment]
> That's exactly what I wanted Do you perhaps by any chance have yt or yt search disabled?

No, I don't have them disabled. Even you set false to it, the discord bot will still use it and console still can see it uses yt search
```
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 10 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
```

**Comment by Ryan5453** [comment]
Does trying to play a YouTube URL work?

**Comment by MikuMikuMe** [comment]
> 



> That's exactly what I wanted Do you perhaps by any chance have yt or yt search disabled?

No, `No matches found for - https://www.youtube.com/watch?v=uVeSf_vIeAE&list=RDuVeSf_vIeAE&start_radio=1`

**Comment by topi314** [comment]
There is literally a false for yt in your yml

**Comment by MikuMikuMe** [comment]
> Does trying to play a YouTube URL work?

If you want me to set true for Youtube in application.yml, I also did that with the youtube link. It doesn't work.
```
2022-08-22 19:29:08.591  INFO 16947 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 16.0.1 on lava.islantay.tk with PID 16947 (/root/lavalink/Lavalink.jar started by root in /root/lavalink)
2022-08-22 19:29:08.594  INFO 16947 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 19:29:10.480  INFO 16947 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.676 seconds (JVM running for 3.437)
2022-08-22 19:29:10.485  INFO 16947 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2022-08-22 19:29:10.596  INFO 16947 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

	Version:        3.5-rc4
	Build time:     18.08.2022 16:03:31 UTC
	Branch          HEAD
	Commit:         b69f613
	Commit time:    18.08.2022 15:52:23 UTC
	JVM:            16.0.1
	Lavaplayer      1.3.98.4-original

2022-08-22 19:29:10.604  INFO 16947 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 19:29:11.829  WARN 16947 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-22 19:29:11.868  INFO 16947 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-22 19:29:11.869  INFO 16947 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1250 ms
2022-08-22 19:29:11.995  WARN 16947 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-22 19:29:12.387  INFO 16947 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-22 19:29:12.712  INFO 16947 --- [           main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
2022-08-22 19:29:12.712  INFO 16947 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-22 19:29:12.716  INFO 16947 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-22 19:29:12.724  INFO 16947 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-22 19:29:13.242  INFO 16947 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2022-08-22 19:29:13.254  INFO 16947 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2022-08-22 19:29:13.277  INFO 16947 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2022-08-22 19:29:13.400  INFO 16947 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2022-08-22 19:29:13.471  INFO 16947 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8880 (http)
2022-08-22 19:29:13.480  INFO 16947 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.983 seconds (JVM running for 6.437)
2022-08-22 19:29:13.489  INFO 16947 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2022-08-22 19:29:23.335  INFO 16947 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-22 19:29:23.339  INFO 16947 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-22 19:29:23.341  INFO 16947 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2022-08-22 19:29:23.365  INFO 16947 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:44342
2022-08-22 19:29:23.463  INFO 16947 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:29:24.845 ERROR 16947 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:44344
2022-08-22 19:29:25.047  INFO 16947 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:44346
2022-08-22 19:29:25.054  INFO 16947 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Wavelink
2022-08-22 19:29:25.947  INFO 16947 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"553794295526588434","volume":100}
2022-08-22 19:29:25.970  INFO 16947 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:never gonna give you up"
2022-08-22 19:29:26.064  INFO 16947 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"sessionId":"92ba1a979ed284d270b9e41b4689e12d","op":"voiceUpdate","guildId":"553794295526588434","event":{"token":"3c72c06fbcb71dac","guild_id":"553794295526588434","endpoint":"us-west6586.discord.media:443"}}
2022-08-22 19:29:27.194  INFO 16947 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: never gonna give you up
2022-08-22 19:29:42.030  INFO 16947 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:33172
2022-08-22 19:29:42.037  INFO 16947 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from WaveLink
2022-08-22 19:29:42.062  INFO 16947 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "216ea91636bf9f36", "timeout": 60}
2022-08-22 19:30:12.524  INFO 16947 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Mic"
2022-08-22 19:30:13.051  INFO 16947 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Mic
2022-08-22 19:30:38.444  INFO 16947 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=EumXak7TyQ0"
2022-08-22 19:30:38.448  WARN 16947 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2022-08-22 19:30:38.948  INFO 16947 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Why I Don't Use Else When Programming
2022-08-22 19:31:25.780  INFO 16947 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=uVeSf_vIeAE&list=RDuVeSf_vIeAE&start_radio=1"
2022-08-22 19:31:26.361  INFO 16947 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Mix - 【HD】Sleepless Nights - Aimer - Re:pray【ENG Sub】
```

**Comment by MikuMikuMe** [comment]
> There is literally a false for yt in your yml

I turned that off because I was suspecting it is youtube's issue

**Comment by topi314** [comment]
Well you can clearly see it providing a result now

How do you expect yt to work when you disable it lmao

**Comment by MikuMikuMe** [comment]
> Well you can clearly see it providing a result now
> 
> How do you expect yt to work when you disable it lmao

But still gives `No matches found for - Musicname`

Btw, V3.4 also could work without errors.

**Comment by topi314** [comment]
No I can't see that in the logs. This was resolved by upgrading to `3.5-rc4`

**Comment by MikuMikuMe** [comment]
> No I can't see that in the logs. This was resolved by upgrading to `3.5-rc4`

The error on the top
`(java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating)`
was actually caused by `v3.5-rc2/3/4`. I was running lavalink with supervisor, I replaced the old `3.4` with `3.5-rc4`, I don't know why in log file it still shows as 3.4. I have installed `v3.4` again and here is the log, It gives errors to youtube link but it works when you try to search with keywords.

```
2022-08-22 19:46:03.639  INFO 18381 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

	Version:        3.4
	Build:          1257
	Build time:     26.10.2021 14:18:37 UTC
	Branch          master
	Commit:         a364833
	Commit time:    26.10.2021 14:15:20 UTC
	JVM:            16.0.1
	Lavaplayer      1.3.96-original

2022-08-22 19:46:03.809  INFO 18381 --- [           main] lavalink.server.Launcher                 : Starting Launcher on lava.islantay.tk with PID 18381 (/root/lavalink/Lavalink.jar started by root in /root/lavalink)
2022-08-22 19:46:03.815  INFO 18381 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2022-08-22 19:46:03.950  WARN 18381 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2022-08-22 19:46:05.645  WARN 18381 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-22 19:46:05.670  INFO 18381 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-22 19:46:05.670  INFO 18381 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1755 ms
2022-08-22 19:46:06.016  WARN 18381 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-22 19:46:06.464  INFO 18381 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-22 19:46:06.717  INFO 18381 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Linux, Arch: amd64
2022-08-22 19:46:06.718  INFO 18381 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-22 19:46:06.720  INFO 18381 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-22 19:46:06.723  INFO 18381 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-22 19:46:07.135  INFO 18381 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-08-22 19:46:07.627  INFO 18381 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2022-08-22 19:46:07.641  INFO 18381 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2022-08-22 19:46:07.724  INFO 18381 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 8880 (http) with context path ''
2022-08-22 19:46:07.732  INFO 18381 --- [           main] lavalink.server.Launcher                 : Started Launcher in 5.057 seconds (JVM running for 5.812)
2022-08-22 19:46:07.733  INFO 18381 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2022-08-22 19:46:08.788  INFO 18381 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-22 19:46:08.788  INFO 18381 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-22 19:46:08.803  INFO 18381 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 14 ms
2022-08-22 19:46:08.828  INFO 18381 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:34140
2022-08-22 19:46:08.893  INFO 18381 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from WaveLink
2022-08-22 19:46:08.923  INFO 18381 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "216ea91636bf9f36", "timeout": 60}
2022-08-22 19:46:11.563 ERROR 18381 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:34150
2022-08-22 19:46:11.783  INFO 18381 --- [  XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59688
2022-08-22 19:46:11.785  INFO 18381 --- [  XNIO-1 task-3] lavalink.server.io.SocketServer          : Connection successfully established from Wavelink
2022-08-22 19:46:14.792  INFO 18381 --- [  XNIO-1 task-4] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59690
2022-08-22 19:46:14.796  INFO 18381 --- [  XNIO-1 task-4] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 19:46:19.080  INFO 18381 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"553794295526588434","volume":100}
2022-08-22 19:46:19.125  INFO 18381 --- [  XNIO-1 task-5] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=uVeSf_vIeAE&list=RDuVeSf_vIeAE&start_radio=1"
2022-08-22 19:46:19.249  INFO 18381 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"sessionId":"ac88127ebb89a791f2962ecb3a3b6e57","op":"voiceUpdate","guildId":"553794295526588434","event":{"token":"6c9431df6de6003f","guild_id":"553794295526588434","endpoint":"us-west6586.discord.media:443"}}
2022-08-22 19:46:19.823 ERROR 18381 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-124-generic
  java.vendor: Private Build
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-Ubuntu-120.04
  java.vm.version: 16.0.1+9-Ubuntu-120.04

2022-08-22 19:46:19.829 ERROR 18381 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-124-generic
  java.vendor: Private Build
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-Ubuntu-120.04
  java.vm.version: 16.0.1+9-Ubuntu-120.04

2022-08-22 19:46:26.495  INFO 18381 --- [  XNIO-1 task-7] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:44754
2022-08-22 19:46:26.500  INFO 18381 --- [  XNIO-1 task-7] lavalink.server.io.SocketServer          : Connection successfully established from DiscordMusic/v5.0.0-beta (Bot: 980797090718433301)
2022-08-22 19:46:40.147  INFO 18381 --- [  XNIO-1 task-8] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:never gonna give you up"
2022-08-22 19:46:40.148  INFO 18381 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found
```

**Comment by aikaterna** [comment]
> The error on the top`(java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating)` was actually caused by v3.5-rc2/3/4

That usually only appears when a connection is closed or the jar is shutting down. Please use the RC4 jar and provide a full log.

**Comment by devoxin** [comment]
Okay so this is getting nowhere and we're just going in circles.

You're providing `No matches found` logs for an outdated Lavalink build, this was a known issue that has been resolved in `rc3` and `rc4`.

`Thread is terminating` is caused by your Lavalink jar quitting, or the websocket connection between Lavalink and your bot closing, as evidenced by the lines in your log resembling:
```
2022-08-22 00:15:55.482  INFO 264186 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:35822 -- CloseStatus[code=1006, reason=]
```

Closing this issue as resolved for now. If there's further discussion to be had, please direct it into the Discord server linked in README.

**Comment by MikuMikuMe** [comment]
> > The error on the top`(java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating)` was actually caused by v3.5-rc2/3/4
> 
> That usually only appears when a connection is closed or the jar is shutting down. Please use the RC4 jar and provide a full log.

```
2022-08-22 20:34:28.832  INFO 22582 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 16.0.1 on lava.islantay.tk with PID 22582 (/root/lavalink/Lavalink.jar started by root in /root/lavalink)
2022-08-22 20:34:28.840  INFO 22582 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 20:34:30.775  INFO 22582 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.802 seconds (JVM running for 3.553)
2022-08-22 20:34:30.787  INFO 22582 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2022-08-22 20:34:30.895  INFO 22582 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

	Version:        3.5-rc4
	Build time:     18.08.2022 16:03:31 UTC
	Branch          HEAD
	Commit:         b69f613
	Commit time:    18.08.2022 15:52:23 UTC
	JVM:            16.0.1
	Lavaplayer      1.3.98.4-original

2022-08-22 20:34:30.908  INFO 22582 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-22 20:34:31.968  WARN 22582 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-22 20:34:32.004  INFO 22582 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-22 20:34:32.004  INFO 22582 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1081 ms
2022-08-22 20:34:32.127  WARN 22582 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-22 20:34:32.535  INFO 22582 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-22 20:34:32.746  INFO 22582 --- [           main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
2022-08-22 20:34:32.746  INFO 22582 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-22 20:34:32.749  INFO 22582 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-22 20:34:32.755  INFO 22582 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-22 20:34:33.254  INFO 22582 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2022-08-22 20:34:33.266  INFO 22582 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2022-08-22 20:34:33.291  INFO 22582 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2022-08-22 20:34:33.412  INFO 22582 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2022-08-22 20:34:33.477  INFO 22582 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8880 (http)
2022-08-22 20:34:33.485  INFO 22582 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.689 seconds (JVM running for 6.264)
2022-08-22 20:34:33.491  INFO 22582 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2022-08-22 20:34:35.022  INFO 22582 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-22 20:34:35.023  INFO 22582 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-22 20:34:35.025  INFO 22582 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2022-08-22 20:34:35.046 ERROR 22582 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:59374
2022-08-22 20:34:35.293  INFO 22582 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59376
2022-08-22 20:34:35.337  INFO 22582 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Wavelink
2022-08-22 20:34:36.484  INFO 22582 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59378
2022-08-22 20:34:36.487  INFO 22582 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from WaveLink
2022-08-22 20:34:36.518  INFO 22582 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "216ea91636bf9f36", "timeout": 60}
2022-08-22 20:38:36.600  INFO 22582 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:40306
2022-08-22 20:38:36.603  INFO 22582 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from DiscordMusic/v5.0.0-beta (Bot: 980797090718433301)
2022-08-22 20:43:03.016  INFO 22582 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:53612
2022-08-22 20:43:03.024  INFO 22582 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-08-22 20:43:22.358  INFO 22582 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"553794295526588434","volume":100}
2022-08-22 20:43:22.401  INFO 22582 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=uVeSf_vIeAE&list=RDuVeSf_vIeAE&start_radio=1"
2022-08-22 20:43:22.714  INFO 22582 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"3a7a7fe05f0143cf500da1d14cedd91f","op":"voiceUpdate","guildId":"553794295526588434","event":{"token":"a8d46b84e349df48","guild_id":"553794295526588434","endpoint":"us-west6643.discord.media:443"}}
2022-08-22 20:43:23.049 ERROR 22582 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-124-generic
  java.vendor: Private Build
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-Ubuntu-120.04
  java.vm.version: 16.0.1+9-Ubuntu-120.04

2022-08-22 20:43:23.060 ERROR 22582 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-124-generic
  java.vendor: Private Build
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-Ubuntu-120.04
  java.vm.version: 16.0.1+9-Ubuntu-120.04

2022-08-22 20:45:23.104  INFO 22582 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Mic"
2022-08-22 20:45:23.105  INFO 22582 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found
```

**Comment by MikuMikuMe** [comment]
> Okay so this is getting nowhere and we're just going in circles.
> 
> You're providing `No matches found` logs for an outdated Lavalink build, this was a known issue that has been resolved in `rc3` and `rc4`.
> 
> `Thread is terminating` is caused by your Lavalink jar quitting, or the websocket connection between Lavalink and your bot closing, as evidenced by the lines in your log resembling:
> 
> ```
> 2022-08-22 00:15:55.482  INFO 264186 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:35822 -- CloseStatus[code=1006, reason=]
> ```
> 
> Closing this issue as resolved for now. If there's further discussion to be had, please direct it into the Discord server linked in README.

You can see even in `3.5-rc4` it is still no matches found.

**Comment by devoxin** [comment]
Misconfigured Lavalink. Again, please redirect your discussion to the Discord server. That URL works for me on the rc4 Lavalink build.
![](https://serux.pro/e729bfc3a0.png)
